config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  root  "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	has_attached_file :product_image, styles: { product_index: "250x300>", product_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :product_image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :find_product, only: [:show,:edit,:update,:destroy]
	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to products_path
		else redirect_to 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @product.update(product_params)
			redirect_to products_path
		else render 'edit'
		end
	end
	
	def destroy
	end

	private
	def product_params
		params.require(:product).permit(:name,:description,:price,:no_of_stock, :size, :product_image)
	end
	def find_product
		@product = Product.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" >    
  <div style="background-color: #232F3E" class="container-fluid ">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header" >
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" style="color: white">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <h2 class="brand brand-name navbar-left">
           <a href="/products#index"><img class="img-responsive2"       
           src="/assets/DigitalPondlogo2.png">eShop</a>
       </h2>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in?%>
        <li><%= link_to "Sign Up", new_user_registration_path ,style:"color: white",class: "navbar-brand"%></li>
        <% else %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :Delete ,style:"color: white",class: "navbar-brand"%></li>
        <% end %>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "layouts/header" %>
  	<div class="container-fluid">
    	<%= yield %>
  	</div>
  </body>
    <nav class="navbar navbar-default" >    
      <div class="container-fluid ">
        <div style="background-color: #485769" class="row">
          <p class="text-center text text" >Back to top</p>
        </div>
        <div style="background-color: #232F3E" class="row">
          <div class="col-md-2">
          </div>
          <div class="col-md-2">
            <ul><h4 class="text">Get to Know Us</h4></ul>
            <ul><p class="text">About Us</p></ul>
            <ul><p class="text">Careers</p></ul>
            <ul><p class="text">Press Releases</p></ul>
            <ul><p class="text">eShop Cares</p></ul>
            <ul><p class="text">Gift a Smile</p></ul>
          </div>

          <div class="col-md-2">
            <ul><h4 class="text">Connect with Us</h4></ul>
            <ul><p class="text">Facebook</p></ul>
            <ul><p class="text">Twitter</p></ul>
            <ul><p class="text">Instagram</p></ul>
          </div>

          <div class="col-md-3">
            <ul><h4 class="text">Make Money with Us</h4></ul>
            <ul><p class="text">Sell on eShop</p></ul>
            <ul><p class="text">Become an Affiliate</p></ul>
            <ul><p class="text">Fulfilment by Amazon</p></ul>
            <ul><p class="text">Advertise Your Products</p></ul>
          </div>

          <div class="col-md-3">
            <ul><h4 class="text">Let Us Help You</h4></ul>
            <ul><p class="text">Your Account</p></ul>
            <ul><p class="text">Returns Centre</p></ul>
            <ul><p class="text">100% Purchase Protection</p></ul>
            <ul><p class="text">eShop Assistant</p></ul>
            <ul><p class="text">Help</p></ul>
          </div>
        </div>
      </div>
    </nav>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.file_field :product_image %>
  <%= f.input :name,label: 'Product Name', error: 'Username is mandatory, please specify one' %>
  <%= f.input :description,label: 'Description' %>
  <%= f.input :price %>
  <%= f.input :no_of_stock %>
  <%= f.input :size %>
  <%= f.button :submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Your Product</h1>
<%= render 'form'%>

app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid margin">
   
  <div id="myCarousel" class="carousel slide margin" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="/assets/1059379_3000x600._CB503546742_.jpg" alt="Los Angeles">
      </div>

      <div class="item">
        <img src="/assets/IN-PR-GW-MultiBen-3000x600._CB503564912_.jpg" alt="Chicago">
      </div>
    
      <div class="item">
        <img src="/assets/3000x600-samsung-mobile-fest-2._CB503559577_.jpg" alt="New York">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
	<% i = 0 %>
<% @products.each do |product|%>
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<% if i % 2 == 0 %>
				<a href="/products/<%=product.id%>"> 
					<%= image_tag product.product_image.url(:product_index)%>
				</a>
			<% end %>
		</div>
		<div class="col-md-6">
			<% if i % 2 != 0 %>
				<a href="/products/<%=product.id%>"> 
					<%= image_tag product.product_image.url(:product_index)%>
				</a>
			<% end %>
		</div>

	</div>
</div>

<% i += 1 %>
<% end %>
</body>
</html>

app/views/products/new.html.erb
<h1>Enter Your Exclusive Product</h1>
<%= render "form"%>

app/views/products/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-5">
			<%= image_tag @product.product_image.url(:product_show)%>
		</div>
		<div class="col-md-7">
			<h1><%= @product.name%></h1>
<blockquote>
	<h2>$<%= @product.price%></h2>
	<p><%= @product.description %></p>
	<p><strong>No.of Stock <%= @product.no_of_stock%></strong></p>
</blockquote>
		</div>
	</div>
</div>

<%= link_to "Edit Product", edit_product_path%>
<%= link_to "Back", root_path%>
<%= link_to "Delete Product", product_path(@product), method: :Delete, data: {confirm: "Are you sure?" }%>